version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data

